export const SHOW_CONFIRM_CODE = 'SHOW_CONFIRM_CODE';
export const SHOW_REGISTER_SCREEN = 'SHOW_REGISTER_SCREEN';
export const USER_DATA_LOADED = 'USER_DATA_LOADED';
export const GET_ALL_BREEDS_ATTEMPT = 'GET_ALL_BREEDS_ATTEMPT';
export const ALL_BREEDS_LOADED = 'ALL_BREEDS_LOADED';
export const ALL_BREEDS_FAILED = 'ALL_BREEDS_FAILED';
